apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: install
  namespace: mt-wac-project
spec:
  wait: true
  force: true
  dependsOn:
  - name: prepare
  interval: 120s
  path: clusters/localhost/install
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-repo