apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: mt-consulting-ufe
  namespace: mt-wac-project
spec:
  imageRepositoryRef:
    name: mt-consulting-ufe # referuje ImageRepository z predchádzajúceho kroku
  filterTags:
      pattern: "main.*" # vyberie všetky verzie, ktoré začínajú na main- (napr. main-20240315.1200)
  policy:
    alphabetical:
      order: asc