apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mt-wac-project

labels:
- pairs:
    app.kubernetes.io/part-of: mt-wac-project
    app.kubernetes.io/name: mt-consulting-ufe
  includeSelectors: true
  includeTemplates: true

resources:
- ../../../apps/mt-consulting-ufe


components:
- ../../../components/version-release