apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: mt-consulting-ufe-content
spec:
  microFrontend: mt-consulting-ufe
  element: consultation-form
  attributes:
    - name: api-base
      value: http://localhost:30081/api
    - name: base-path
      value: /
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?mt-consulting-ufe(/.*)?$"